/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pedrapapeltesoura;

import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JToggleButton;

/**
 *
 * @author Usuario
 */
public class PedraPapelTesoura extends javax.swing.JFrame {

    public PedraPapelTesoura(JLabel jLabPergunta, JLabel jLabResultado, JRadioButton jRdBtPapel, JRadioButton jRdBtPedra, JToggleButton jRdBtResposta, JRadioButton jRdBtTesoura) {
        this.jLabPergunta = jLabPergunta;
        this.jLabResultado = jLabResultado;
        this.jRdBtPapel = jRdBtPapel;
        this.jRdBtPedra = jRdBtPedra;
        this.jRdBtResposta = jRdBtResposta;
        this.jRdBtTesoura = jRdBtTesoura;
    }

    public JLabel getjLabPergunta() {
        return jLabPergunta;
    }

    public void setjLabPergunta(JLabel jLabPergunta) {
        this.jLabPergunta = jLabPergunta;
    }

    public JLabel getjLabResultado() {
        return jLabResultado;
    }

    public void setjLabResultado(JLabel jLabResultado) {
        this.jLabResultado = jLabResultado;
    }

    public JRadioButton getjRdBtPapel() {
        return jRdBtPapel;
    }

    public void setjRdBtPapel(JRadioButton jRdBtPapel) {
        this.jRdBtPapel = jRdBtPapel;
    }

    public JRadioButton getjRdBtPedra() {
        return jRdBtPedra;
    }

    public void setjRdBtPedra(JRadioButton jRdBtPedra) {
        this.jRdBtPedra = jRdBtPedra;
    }

    public JToggleButton getjRdBtResposta() {
        return jRdBtResposta;
    }

    public void setjRdBtResposta(JToggleButton jRdBtResposta) {
        this.jRdBtResposta = jRdBtResposta;
    }

    public JRadioButton getjRdBtTesoura() {
        return jRdBtTesoura;
    }

    public void setjRdBtTesoura(JRadioButton jRdBtTesoura) {
        this.jRdBtTesoura = jRdBtTesoura;
    }

    /**
     * Creates new form JogodaDaVelha
     */
    public PedraPapelTesoura() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabPergunta = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jRdBtPedra = new javax.swing.JRadioButton();
        jRdBtPapel = new javax.swing.JRadioButton();
        jRdBtTesoura = new javax.swing.JRadioButton();
        jRdBtResposta = new javax.swing.JToggleButton();
        jLabResultado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabPergunta.setText("Pedra, Papel ou Tesoura?");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabPergunta)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabPergunta)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jRdBtPedra.setText("Pedra");
        jRdBtPedra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRdBtPedraActionPerformed(evt);
            }
        });

        jRdBtPapel.setText("Papel");
        jRdBtPapel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRdBtPapelActionPerformed(evt);
            }
        });

        jRdBtTesoura.setText("Tesoura");
        jRdBtTesoura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRdBtTesouraActionPerformed(evt);
            }
        });

        jRdBtResposta.setText("Resposta");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRdBtPedra)
                    .addComponent(jRdBtPapel)
                    .addComponent(jRdBtTesoura))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jRdBtResposta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jRdBtPedra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRdBtPapel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRdBtTesoura))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jRdBtResposta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRdBtPedraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRdBtPedraActionPerformed
      JRadioButton pedra = this.getjRdBtPedra();
        JRadioButton papel = this.getjRdBtPapel();
        JRadioButton tesoura = this.getjRdBtTesoura();

        if (pedra.isSelected()) {

            papel.setSelected(false);
            tesoura.setSelected(false);

            pedra.setSelected(true);
        } else {
            papel.setSelected(false);
            tesoura.setSelected(false);

            pedra.setSelected(false);
        }
    }//GEN-LAST:event_jRdBtPedraActionPerformed

    private void jRdBtPapelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRdBtPapelActionPerformed
         JRadioButton pedra = this.getjRdBtPedra();
        JRadioButton papel = this.getjRdBtPapel();
        JRadioButton tesoura = this.getjRdBtTesoura();

        if (papel.isSelected()) {

            pedra.setSelected(false);
            tesoura.setSelected(false);

            papel.setSelected(true);
        } else {
            pedra.setSelected(false);
            tesoura.setSelected(false);

            papel.setSelected(false);
        }
    }//GEN-LAST:event_jRdBtPapelActionPerformed

    private void jRdBtTesouraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRdBtTesouraActionPerformed
      JRadioButton pedra = this.getjRdBtPedra();
        JRadioButton papel = this.getjRdBtPapel();
        JRadioButton tesoura = this.getjRdBtTesoura();

        if (tesoura.isSelected()) {

            pedra.setSelected(false);
            papel.setSelected(false);

            tesoura.setSelected(true);
        } else {
            papel.setSelected(false);
            pedra.setSelected(false);

            tesoura.setSelected(false);
        }
    }//GEN-LAST:event_jRdBtTesouraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PedraPapelTesoura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PedraPapelTesoura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PedraPapelTesoura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PedraPapelTesoura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PedraPapelTesoura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabPergunta;
    private javax.swing.JLabel jLabResultado;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRdBtPapel;
    private javax.swing.JRadioButton jRdBtPedra;
    private javax.swing.JToggleButton jRdBtResposta;
    private javax.swing.JRadioButton jRdBtTesoura;
    // End of variables declaration//GEN-END:variables
}
