/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pesoplanetas;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JTextField;

/**
 *
 * @author Usuario
 */
public class OsPlanetas extends javax.swing.JFrame {

    double peso;
    
    public OsPlanetas(JLabel JLabEscolha, JLabel JLabPeso, JLabel JLabResultado, JButton JbCalcularPeso, JTextField JtxtColocarPeso, JRadioButton RBtnJupiter, JRadioButton RBtnMarte, JRadioButton RBtnMercurio, JRadioButton RBtnSaturno, JRadioButton RBtnUrano, JRadioButton RBtnVenus) {
        this.JLabEscolha = JLabEscolha;
        this.JLabPeso = JLabPeso;
        this.JLabResultado = JLabResultado;
        this.JbCalcularPeso = JbCalcularPeso;
        this.JtxtColocarPeso = JtxtColocarPeso;
        this.RBtnJupiter = RBtnJupiter;
        this.RBtnMarte = RBtnMarte;
        this.RBtnMercurio = RBtnMercurio;
        this.RBtnSaturno = RBtnSaturno;
        this.RBtnUrano = RBtnUrano;
        this.RBtnVenus = RBtnVenus;
    }

    public JLabel getJLabResultado() {
        return JLabResultado;
    }

    public void setJLabResultado(JLabel JLabResultado) {
        this.JLabResultado = JLabResultado;
    }

    public JButton getJbCalcularPeso() {
        return JbCalcularPeso;
    }

    public void setJbCalcularPeso(JButton JbCalcularPeso) {
        this.JbCalcularPeso = JbCalcularPeso;
    }

    public JTextField getJtxtColocarPeso() {
        return JtxtColocarPeso;
    }

    public void setJtxtColocarPeso(JTextField JtxtColocarPeso) {
        this.JtxtColocarPeso = JtxtColocarPeso;
    }

    public JRadioButton getRBtnJupiter() {
        return RBtnJupiter;
    }

    public void setRBtnJupiter(JRadioButton RBtnJupiter) {
        this.RBtnJupiter = RBtnJupiter;
    }

    public JRadioButton getRBtnMarte() {
        return RBtnMarte;
    }

    public void setRBtnMarte(JRadioButton RBtnMarte) {
        this.RBtnMarte = RBtnMarte;
    }

    public JRadioButton getRBtnMercurio() {
        return RBtnMercurio;
    }

    public void setRBtnMercurio(JRadioButton RBtnMercurio) {
        this.RBtnMercurio = RBtnMercurio;
    }

    public JRadioButton getRBtnSaturno() {
        return RBtnSaturno;
    }

    public void setRBtnSaturno(JRadioButton RBtnSaturno) {
        this.RBtnSaturno = RBtnSaturno;
    }

    public JRadioButton getRBtnUrano() {
        return RBtnUrano;
    }

    public void setRBtnUrano(JRadioButton RBtnUrano) {
        this.RBtnUrano = RBtnUrano;
    }

    public JRadioButton getRBtnVenus() {
        return RBtnVenus;
    }

    public void setRBtnVenus(JRadioButton RBtnVenus) {
        this.RBtnVenus = RBtnVenus;
    }

    /**
     * Creates new form OsPlanetas
     */
    public OsPlanetas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        JtxtColocarPeso = new javax.swing.JTextField();
        JbCalcularPeso = new javax.swing.JButton();
        JLabPeso = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        RBtnMercurio = new javax.swing.JRadioButton();
        RBtnVenus = new javax.swing.JRadioButton();
        RBtnMarte = new javax.swing.JRadioButton();
        RBtnJupiter = new javax.swing.JRadioButton();
        RBtnSaturno = new javax.swing.JRadioButton();
        RBtnUrano = new javax.swing.JRadioButton();
        JLabEscolha = new javax.swing.JLabel();
        JLabResultado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JtxtColocarPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtxtColocarPesoActionPerformed(evt);
            }
        });

        JbCalcularPeso.setText("Calcular peso");
        JbCalcularPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbCalcularPesoActionPerformed(evt);
            }
        });

        JLabPeso.setText("Peso na Terra:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JLabPeso)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(JtxtColocarPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(JbCalcularPeso)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addComponent(JLabPeso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JbCalcularPeso)
                    .addComponent(JtxtColocarPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        RBtnMercurio.setText("Mercurio");
        RBtnMercurio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBtnMercurioActionPerformed(evt);
            }
        });

        RBtnVenus.setText("Venus");
        RBtnVenus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBtnVenusActionPerformed(evt);
            }
        });

        RBtnMarte.setText("Marte");
        RBtnMarte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBtnMarteActionPerformed(evt);
            }
        });

        RBtnJupiter.setText("Jupiter");
        RBtnJupiter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBtnJupiterActionPerformed(evt);
            }
        });

        RBtnSaturno.setText("Saturno");
        RBtnSaturno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBtnSaturnoActionPerformed(evt);
            }
        });

        RBtnUrano.setText("Urano");
        RBtnUrano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBtnUranoActionPerformed(evt);
            }
        });

        JLabEscolha.setText("Escolha o Planeta:");

        JLabResultado.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                JLabResultadoAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(JLabEscolha)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RBtnMercurio)
                            .addComponent(RBtnVenus, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RBtnMarte)
                            .addComponent(RBtnJupiter))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RBtnSaturno)
                            .addComponent(RBtnUrano))
                        .addGap(18, 18, 18)
                        .addComponent(JLabResultado, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)))
                .addGap(6, 6, 6))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(JLabEscolha, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RBtnMercurio)
                            .addComponent(RBtnMarte)
                            .addComponent(RBtnSaturno))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RBtnVenus)
                            .addComponent(RBtnJupiter)
                            .addComponent(RBtnUrano)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(JLabResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RBtnMercurioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBtnMercurioActionPerformed
        JRadioButton mercurio = this.getRBtnMercurio();
        JRadioButton venus = this.getRBtnVenus();
        JRadioButton marte = this.getRBtnMarte();
        JRadioButton jupiter = this.getRBtnJupiter();
        JRadioButton Saturno = this.getRBtnSaturno();
        JRadioButton urano = this.getRBtnUrano();

        if (mercurio.isSelected()) {
            venus.setSelected(false);
            marte.setSelected(false);
            jupiter.setSelected(false);
            Saturno.setSelected(false);
            urano.setSelected(false);

            mercurio.setSelected(true);
        } else {
            venus.setSelected(false);
            marte.setSelected(false);
            jupiter.setSelected(false);
            Saturno.setSelected(false);
            urano.setSelected(false);

            mercurio.setSelected(false);
        }
    }//GEN-LAST:event_RBtnMercurioActionPerformed

    private void RBtnVenusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBtnVenusActionPerformed
        JRadioButton mercurio = this.getRBtnMercurio();
        JRadioButton venus = this.getRBtnVenus();
        JRadioButton marte = this.getRBtnMarte();
        JRadioButton jupiter = this.getRBtnJupiter();
        JRadioButton saturno = this.getRBtnSaturno();
        JRadioButton urano = this.getRBtnUrano();

        if (venus.isSelected()) {
            mercurio.setSelected(false);
            marte.setSelected(false);
            jupiter.setSelected(false);
            saturno.setSelected(false);
            urano.setSelected(false);

            venus.setSelected(true);
        } else {
            mercurio.setSelected(false);
            marte.setSelected(false);
            jupiter.setSelected(false);
            saturno.setSelected(false);
            urano.setSelected(false);

            venus.setSelected(false);
        }
    }//GEN-LAST:event_RBtnVenusActionPerformed

    private void RBtnJupiterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBtnJupiterActionPerformed
        JRadioButton mercurio = this.getRBtnMercurio();
        JRadioButton venus = this.getRBtnVenus();
        JRadioButton marte = this.getRBtnMarte();
        JRadioButton jupiter = this.getRBtnJupiter();
        JRadioButton saturno = this.getRBtnSaturno();
        JRadioButton urano = this.getRBtnUrano();

        if (jupiter.isSelected()) {
            venus.setSelected(false);
            marte.setSelected(false);
            mercurio.setSelected(false);
            saturno.setSelected(false);
            urano.setSelected(false);

            jupiter.setSelected(true);
        } else {
            venus.setSelected(false);
            marte.setSelected(false);
            mercurio.setSelected(false);
            saturno.setSelected(false);
            urano.setSelected(false);

            jupiter.setSelected(false);
        }
    }//GEN-LAST:event_RBtnJupiterActionPerformed

    private void RBtnUranoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBtnUranoActionPerformed
        JRadioButton mercurio = this.getRBtnMercurio();
        JRadioButton venus = this.getRBtnVenus();
        JRadioButton marte = this.getRBtnMarte();
        JRadioButton jupiter = this.getRBtnJupiter();
        JRadioButton saturno = this.getRBtnSaturno();
        JRadioButton urano = this.getRBtnUrano();

        if (urano.isSelected()) {
            venus.setSelected(false);
            marte.setSelected(false);
            jupiter.setSelected(false);
            saturno.setSelected(false);
            mercurio.setSelected(false);

            urano.setSelected(true);
        } else {
            venus.setSelected(false);
            marte.setSelected(false);
            jupiter.setSelected(false);
            saturno.setSelected(false);
            mercurio.setSelected(false);

            urano.setSelected(false);
        }
    }//GEN-LAST:event_RBtnUranoActionPerformed

    private void RBtnMarteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBtnMarteActionPerformed
        JRadioButton mercurio = this.getRBtnMercurio();
        JRadioButton venus = this.getRBtnVenus();
        JRadioButton marte = this.getRBtnMarte();
        JRadioButton jupiter = this.getRBtnJupiter();
        JRadioButton saturno = this.getRBtnSaturno();
        JRadioButton urano = this.getRBtnUrano();

        if (marte.isSelected()) {
            venus.setSelected(false);
            mercurio.setSelected(false);
            jupiter.setSelected(false);
            saturno.setSelected(false);
            urano.setSelected(false);

            marte.setSelected(true);
        } else {
            venus.setSelected(false);
            mercurio.setSelected(false);
            jupiter.setSelected(false);
            saturno.setSelected(false);
            urano.setSelected(false);

            marte.setSelected(false);
        }
    }//GEN-LAST:event_RBtnMarteActionPerformed

    private void RBtnSaturnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBtnSaturnoActionPerformed
        JRadioButton mercurio = this.getRBtnMercurio();
        JRadioButton venus = this.getRBtnVenus();
        JRadioButton marte = this.getRBtnMarte();
        JRadioButton jupiter = this.getRBtnJupiter();
        JRadioButton saturno = this.getRBtnSaturno();
        JRadioButton urano = this.getRBtnUrano();

        if (saturno.isSelected()) {
            venus.setSelected(false);
            marte.setSelected(false);
            jupiter.setSelected(false);
            mercurio.setSelected(false);
            urano.setSelected(false);

            saturno.setSelected(true);
        } else {
            venus.setSelected(false);
            marte.setSelected(false);
            jupiter.setSelected(false);
            mercurio.setSelected(false);
            urano.setSelected(false);

            saturno.setSelected(false);
        }
    }//GEN-LAST:event_RBtnSaturnoActionPerformed

    private void JbCalcularPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbCalcularPesoActionPerformed
        JRadioButton mercurio = this.getRBtnMercurio();
    JRadioButton venus = this.getRBtnVenus();
    JRadioButton marte = this.getRBtnMarte();
    JRadioButton jupiter = this.getRBtnJupiter();
    JRadioButton saturno = this.getRBtnSaturno();
    JRadioButton urano = this.getRBtnUrano();
    JTextField pesoField = this.getJtxtColocarPeso();
    JLabel resultado = this.getJLabResultado();

    double calculo = 0;
    String pesoText = pesoField.getText();
    
    try {
        double peso = Double.parseDouble(pesoText);

        if (mercurio.isSelected()) {
            calculo = (peso * 0.37) / 10;

            resultado.setText(String.format("Peso em Mercúrio: %.2f", calculo));
            JOptionPane.showMessageDialog(this, String.format("Peso em Mercúrio: %.2f", calculo));
        }

    } catch (NumberFormatException e) {
        resultado.setText("Por favor, insira um valor válido para o peso.");
    }
    
    try {
        double peso = Double.parseDouble(pesoText);

        if (venus.isSelected()) {
            calculo = (peso/10)*0.88;

            resultado.setText(String.format("Peso em Venus: %.2f", calculo));
            JOptionPane.showMessageDialog(this, String.format("Peso em Venus: %.2f", calculo));
        }

    } catch (NumberFormatException e) {
        resultado.setText("Por favor, insira um valor válido para o peso.");
    }
      try {
        double peso = Double.parseDouble(pesoText);

        if (marte.isSelected()) {
            calculo = (peso/10)*0.38;

            resultado.setText(String.format("Peso em Marte: %.2f", calculo));
            JOptionPane.showMessageDialog(this, String.format("Peso em Marte: %.2f", calculo));
        }

    } catch (NumberFormatException e) {
        resultado.setText("Por favor, insira um valor válido para o peso.");
    }
      try {
        double peso = Double.parseDouble(pesoText);

        if (jupiter.isSelected()) {
            calculo = (peso/10)*2.64;

            resultado.setText(String.format("Peso em Jupiter: %.2f", calculo));
            JOptionPane.showMessageDialog(this, String.format("Peso em Jupiter: %.2f", calculo));
        }

    } catch (NumberFormatException e) {
        resultado.setText("Por favor, insira um valor válido para o peso.");
    }
      try {
        double peso = Double.parseDouble(pesoText);

        if (saturno.isSelected()) {
            calculo = (peso/10)*1.15;

            resultado.setText(String.format("Peso em Saturno: %.2f", calculo));
            JOptionPane.showMessageDialog(this, String.format("Peso em Saturno: %.2f", calculo));
        }

    } catch (NumberFormatException e) {
        resultado.setText("Por favor, insira um valor válido para o peso.");
    }
      try {
        double peso = Double.parseDouble(pesoText);

        if (urano.isSelected()) {
            calculo = (peso/10)*1.17;

            resultado.setText(String.format("Peso em Urano: %.2f", calculo));
            JOptionPane.showMessageDialog(this, String.format("Peso em Urano: %.2f", calculo));
        }

    } catch (NumberFormatException e) {
        resultado.setText("Por favor, insira um valor válido para o peso.");
    }
      
    }//GEN-LAST:event_JbCalcularPesoActionPerformed

    private void JtxtColocarPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtxtColocarPesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtxtColocarPesoActionPerformed

    private void JLabResultadoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_JLabResultadoAncestorAdded

    }//GEN-LAST:event_JLabResultadoAncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OsPlanetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OsPlanetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OsPlanetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OsPlanetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OsPlanetas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabEscolha;
    private javax.swing.JLabel JLabPeso;
    private javax.swing.JLabel JLabResultado;
    private javax.swing.JButton JbCalcularPeso;
    private javax.swing.JTextField JtxtColocarPeso;
    private javax.swing.JRadioButton RBtnJupiter;
    private javax.swing.JRadioButton RBtnMarte;
    private javax.swing.JRadioButton RBtnMercurio;
    private javax.swing.JRadioButton RBtnSaturno;
    private javax.swing.JRadioButton RBtnUrano;
    private javax.swing.JRadioButton RBtnVenus;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
