/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sosrs;

import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 03824366010
 */
public class VinculoDoenca extends javax.swing.JFrame {

    /**
     * Creates new form VinculoDoenca
     */
    public VinculoDoenca() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TodosPanel = new javax.swing.JPanel();
        PanelSos = new javax.swing.JPanel();
        sosRS = new javax.swing.JLabel();
        PanelDescricao = new javax.swing.JPanel();
        jLabelDigitarDoenca = new javax.swing.JLabel();
        txtEscreverDoenca = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        jLabelDoencaLocalizada = new javax.swing.JLabel();
        txtRetornoDoenca = new javax.swing.JTextField();
        btnVincularSintoma = new javax.swing.JButton();
        jScrollTabelaSintoma = new javax.swing.JScrollPane();
        jTableResultado = new javax.swing.JTable();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sosRS.setFont(new java.awt.Font("Sitka Subheading", 0, 40)); // NOI18N
        sosRS.setText("SOS RS");

        javax.swing.GroupLayout PanelSosLayout = new javax.swing.GroupLayout(PanelSos);
        PanelSos.setLayout(PanelSosLayout);
        PanelSosLayout.setHorizontalGroup(
            PanelSosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSosLayout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(sosRS)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelSosLayout.setVerticalGroup(
            PanelSosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelSosLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(sosRS)
                .addContainerGap())
        );

        jLabelDigitarDoenca.setText("Digite a Doença:");

        txtEscreverDoenca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEscreverDoencaActionPerformed(evt);
            }
        });

        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        jLabelDoencaLocalizada.setText("DOENÇA LOCALIZADA");

        txtRetornoDoenca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRetornoDoencaActionPerformed(evt);
            }
        });

        btnVincularSintoma.setText("Vincular Sintomas");
        btnVincularSintoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVincularSintomaActionPerformed(evt);
            }
        });

        jTableResultado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"rodolfo"},
                {null}
            },
            new String [] {
                "Sintoma"
            }
        ));
        jScrollTabelaSintoma.setViewportView(jTableResultado);
        if (jTableResultado.getColumnModel().getColumnCount() > 0) {
            jTableResultado.getColumnModel().getColumn(0).setResizable(false);
        }

        btnAlterar.setText("Alterar");

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelDescricaoLayout = new javax.swing.GroupLayout(PanelDescricao);
        PanelDescricao.setLayout(PanelDescricaoLayout);
        PanelDescricaoLayout.setHorizontalGroup(
            PanelDescricaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDescricaoLayout.createSequentialGroup()
                .addGroup(PanelDescricaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelDescricaoLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabelDoencaLocalizada))
                    .addGroup(PanelDescricaoLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(PanelDescricaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtRetornoDoenca, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelDescricaoLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(txtEscreverDoenca, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(PanelDescricaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelDescricaoLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btnVincularSintoma, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelDescricaoLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(btnPesquisar))))
                    .addGroup(PanelDescricaoLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(PanelDescricaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollTabelaSintoma, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PanelDescricaoLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(btnAlterar)
                                .addGap(34, 34, 34)
                                .addComponent(btnExcluir)
                                .addGap(32, 32, 32)
                                .addComponent(btnCancelar))))
                    .addGroup(PanelDescricaoLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabelDigitarDoenca, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        PanelDescricaoLayout.setVerticalGroup(
            PanelDescricaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDescricaoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabelDigitarDoenca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelDescricaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEscreverDoenca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisar))
                .addGap(18, 18, 18)
                .addGroup(PanelDescricaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelDescricaoLayout.createSequentialGroup()
                        .addComponent(jLabelDoencaLocalizada)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRetornoDoenca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnVincularSintoma))
                .addGap(29, 29, 29)
                .addComponent(jScrollTabelaSintoma, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PanelDescricaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAlterar)
                    .addComponent(btnExcluir)
                    .addComponent(btnCancelar))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout TodosPanelLayout = new javax.swing.GroupLayout(TodosPanel);
        TodosPanel.setLayout(TodosPanelLayout);
        TodosPanelLayout.setHorizontalGroup(
            TodosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelSos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PanelDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        TodosPanelLayout.setVerticalGroup(
            TodosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TodosPanelLayout.createSequentialGroup()
                .addComponent(PanelSos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TodosPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TodosPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRetornoDoencaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRetornoDoencaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRetornoDoencaActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnVincularSintomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVincularSintomaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVincularSintomaActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
      txtEscreverDoenca.setText("");
      txtRetornoDoenca.setText("");
      JTable tabelaSintoma = (JTable) jScrollTabelaSintoma.getViewport().getView();
    DefaultTableModel model = (DefaultTableModel) tabelaSintoma.getModel();
    model.setRowCount(0);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtEscreverDoencaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEscreverDoencaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEscreverDoencaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VinculoDoenca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VinculoDoenca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VinculoDoenca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VinculoDoenca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VinculoDoenca().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelDescricao;
    private javax.swing.JPanel PanelSos;
    private javax.swing.JPanel TodosPanel;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnVincularSintoma;
    private javax.swing.JLabel jLabelDigitarDoenca;
    private javax.swing.JLabel jLabelDoencaLocalizada;
    private javax.swing.JScrollPane jScrollTabelaSintoma;
    private javax.swing.JTable jTableResultado;
    private javax.swing.JLabel sosRS;
    private javax.swing.JTextField txtEscreverDoenca;
    private javax.swing.JTextField txtRetornoDoenca;
    // End of variables declaration//GEN-END:variables
}
